server:
  port: 8080

spring:
  application:
    name: restaurant-booking-platform
  
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sandun
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: update

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    com.tabletop: DEBUG
    org.springframework.security: DEBUG

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

